name: documentation

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "metadata-ingestion/**"
      - "metadata-models/**"
      - "docs-website/**"
  push:
    branches:
      - master
    paths:
      - "metadata-ingestion/**"
      - "metadata-models/**"
      - "docs-website/**"
  # release:
  #   types: [published, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: acryldata/sane-checkout-action@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
      - name: Install Python dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Build Docs
        run: |
          ./gradlew --info docs-website:build

      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'datahub-project/datahub'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-website/build
          cname: datahubproject.io
