name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: acryldata/sane-checkout-action@v3
      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2022.3.4
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          cache-default-branch-only: true
